version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_desafio06
    networks:
      - desafio06
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    networks:
      - desafio06
    ports:
      - '8080:8080'

networks:
  desafio06:

volumes:
  db_data:
